Liftai0513/LiftaiMVC/Models/Elevator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Reflection;
using LiftaiMVC.Interfaces;

namespace LiftaiMVC.Models
{
    public class Elevator: IElevator
    {
        public IElevator SelectElevator()
        {
            return this;
        }

        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Serijos numeris")]
        [DataType(DataType.Text)]
        public string SerialNum { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Modelis")]
        [DataType(DataType.Text)]
        public string Model { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Įrengimo data")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DeploymentDate { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Maksimalus svoris (kg)")]
        [Range(1, 5000, ErrorMessage = "Įveskite tinkamą svorį (1-5000)")]
        public int MaxWeight { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Laiptinės numeris")]
        [Range(0, 100, ErrorMessage = "Įveskite tinkamą laiptinės numerį (0-100)")]
        public int Stairway { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Paskutinės profilaktikos data")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime LastCheckUp { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Profilaktikos dažnumas (mėn)")]
        [Range(1, 48, ErrorMessage = "Įveskite tinkamą mėnesių kiekį (1-48)")]
        public int CheckUpFrequency { get; set; }


        // LIFTO BŪKLĖ

        [Display(Name = "Pastabos")]
        [DataType(DataType.MultilineText)]
        public string Notes { get; set; }

        [Required(ErrorMessage = "Būtina užpildyti šį lauką")]
        [Display(Name = "Pastato ID")]
        public string BuildingID { get; set; } // IDETI I UML DIAGRAMA!!!!

        [Required(ErrorMessage = "Būtina pasirinkti būseną")]
        [Display(Name = "Būsena")]
        public States State { get; set; }

        public Elevator()
        {
            DeploymentDate = DateTime.Now.Date;
            MaxWeight = 500;
            Stairway = 0;
            LastCheckUp = DateTime.Now.Date;
            CheckUpFrequency = 12;
        }

        public bool changeState(string state)
        {
            foreach(States st in Enum.GetValues(typeof(States)))
            {
                if (state == st.ToString())
                {
                    this.State = st;
                    return true;
                }
            }
            return false;
        }

        public string StateName()
        {
            return this.State.GetAttribute<DisplayAttribute>().Name;
        }

        public static string StateName(string state)
        {
            States NewState = States.active;
            if (state == "stopped")
                NewState = States.stopped;
            else if (state == "broken")
                NewState = States.broken;
            else if (state == "dead")
                NewState = States.dead;
            else if (state == "repairing")
                NewState = States.repairing;
            return NewState.GetAttribute<DisplayAttribute>().Name;
        }
    }

    public static class Extensions
    {
        /// <summary>
        ///     A generic extension method that aids in reflecting 
        ///     and retrieving any attribute that is applied to an `Enum`.
        /// </summary>
        public static TAttribute GetAttribute<TAttribute>(this Enum enumValue)
                where TAttribute : Attribute
        {
            return enumValue.GetType()
                            .GetMember(enumValue.ToString())
                            .First()
                            .GetCustomAttribute<TAttribute>();
        }
    }

    public enum States
    {
        [Display(Name = "Veikiantis")]
        active,
        [Display(Name = "Sugedęs")]
        broken,
        [Display(Name = "Tvarkomas")]
        repairing,
        [Display(Name = "Nebeveikiantis")]
        dead,
        [Display(Name = "Sustabdytas")]
        stopped
    }
}

Liftai0513/LiftaiMVC/Controllers/ElevatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace LiftaiMVC.Controllers
{
    public class ElevatorsController : Controller
    {
        public void OpenBuildingDetails()
        {
            var elevator = new Models.Elevator().SelectElevator();
        }

        // GET: Elevators
        public ActionResult ElevatorsList()
        {
            try
            {
                ViewBag.Message = "Liftų sąrašas";
                Models.ElevatorsDB db = new Models.ElevatorsDB();
                return View(db.Elevators);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 2";
                return RedirectToAction("Error", "Home");
            }

        }

        [HttpGet]
        public ActionResult ElevatorForm()
        {
            try
            {
                Models.ElevatorsDB db = new Models.ElevatorsDB();
                Models.Elevator NewElevator = new Models.Elevator();
                ViewData["Buildings"] = ToSelectList(db.Buildings);
                return View(NewElevator);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 3";
                return RedirectToAction("Error", "Home");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ElevatorForm(Models.Elevator NewElevator)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Models.ElevatorsDB db = new Models.ElevatorsDB();
                    db.Elevators.Add(NewElevator);
                    db.SaveChanges();
                    TempData["SuccessMessage"] = "Įrašas buvo sėkmingas";
                    return RedirectToAction("ElevatorForm");
                }
                else
                {
                    TempData["SuccessMessage"] = null;
                    Models.ElevatorsDB db = new Models.ElevatorsDB();
                    ViewData["Buildings"] = ToSelectList(db.Buildings);
                }
                return View();
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 4";
                return RedirectToAction("Error", "Home");
            }

        }


        public ActionResult Delete(string id)
        {
            try
            {
                Models.ElevatorsDB db = new Models.ElevatorsDB();
                Models.Elevator elevator = db.Elevators.First(x => x.ID.ToString() == id);
                db.Elevators.Remove(elevator);
                db.SaveChanges();
                return RedirectToAction("ElevatorsList");
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 5";
                return RedirectToAction("Error", "Home");
            }

        }

        [HttpGet]
        public ActionResult DetailedElevatorInfo(int id)
        {
            try
            {
                Models.ElevatorsDB db = new Models.ElevatorsDB();
                ViewData["Buildings"] = ToSelectList(db.Buildings);
                Models.Elevator elevator = db.Elevators.First(x => x.ID == id);
                return View(elevator);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 6";
                return RedirectToAction("Error", "Home");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DetailedElevatorInfo(Models.Elevator elevator)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Models.ElevatorsDB db = new Models.ElevatorsDB();
                    Models.Elevator dbelevator = db.Elevators.First(x => x.ID == elevator.ID);
                    db.Entry(dbelevator).CurrentValues.SetValues(elevator);
                    db.SaveChanges();
                    TempData["EditSuccess"] = "Įrašas buvo sėkmingai redaguotas";
                    return RedirectToAction("DetailedElevatorInfo", new { id = elevator.ID });
                }
                else
                {
                    TempData["EditSuccess"] = null;
                    Models.ElevatorsDB db = new Models.ElevatorsDB();
                    ViewData["Buildings"] = ToSelectList(db.Buildings);
                }
                return View();
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 7";
                return RedirectToAction("Error", "Home");
            }

        }

        [NonAction]
        public SelectList ToSelectList(System.Data.Entity.DbSet buildings)
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();

                foreach (Models.Building building in buildings)
                {
                    list.Add(new SelectListItem()
                    {
                        Text = building.Address,
                        Value = building.id.ToString()
                    });
                }

                return new SelectList(list, "Value", "Text");
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 8";
                return null;
            }

        }

        [HttpGet]
        public ActionResult RestartElevator(int elevatorID, bool? restart)
        {
            try
            {
                Models.ElevatorsDB elevatorsDB = new Models.ElevatorsDB();
                Models.Elevator elevator = elevatorsDB.Elevators.First(x => x.ID == elevatorID);
                if (!restart.HasValue)
                {
                    TempData["EditSuccess"] = "Perkraunama lifto sistema...";
                    return RedirectToAction("ElevatorAPI", new { id = elevatorID });
                }
                else if ((bool)restart)
                    TempData["EditSuccess"] = "Lifto sistema sėkmingai perkrauta " + DateTime.Now.ToLocalTime().ToString();
                else
                    TempData["EditSuccess"] = "Lifto sistemos pekrovimas nepavyko (" + DateTime.Now.ToLocalTime().ToString() + ").";

                // SEND RESTART SIGNAL TO THE ELEVATOR
                // (respond via Elevators/ElevatorAPI/{id}  RESTART button

                return RedirectToAction("DetailedElevatorInfo", new { id = elevatorID });
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 9";
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public ActionResult TurnOffBrakes(int elevatorID, bool? state)
        {
            try
            {
                Models.ElevatorsDB elevatorsDB = new Models.ElevatorsDB();
                Models.Elevator elevator = elevatorsDB.Elevators.First(x => x.ID == elevatorID);
                if (!state.HasValue)
                {
                    TempData["EditSuccess"] = "Klausiama lifto būklės...";
                    // ASK ELEVATOR STATE
                    // (respond via Elevators/ElevatorAPI/{id}  SEND STATE button
                    return RedirectToAction("ElevatorAPI", new { id = elevatorID });
                }
                else if ((bool)state)
                    // SEND BRAKES TURN OFF SIGNAL TO THE ELEVATOR
                    TempData["EditSuccess"] = "Lifto avariniai stabdžiai išjungti " + DateTime.Now.ToLocalTime().ToString();
                else
                    TempData["EditSuccess"] = "Lifto avariniai stabdžiai negali būti išjungti dėl nesaugios lifto būklės (" + DateTime.Now.ToLocalTime().ToString() + ").";

                return RedirectToAction("DetailedElevatorInfo", new { id = elevatorID });

            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 10";
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public ActionResult NewState(int elevatorID, string state)
        {
            try
            {
                Models.ElevatorsDB elevatorsDB = new Models.ElevatorsDB();
                Models.Elevator elevator = elevatorsDB.Elevators.First(x => x.ID == elevatorID);
                string previousState = elevator.State.ToString();

                if (elevator.changeState(state))
                {
                    elevatorsDB.SaveChanges();
                    TempData["EditSuccess"] = "Atnaujinta lifto būklė (" + DateTime.Now.ToLocalTime().ToString() + ").";
                }
                else
                {
                    TempData["EditSuccess"] = "Gautas nežinomos būklės signalas (" + DateTime.Now.ToLocalTime().ToString() + ").";
                }

                if (state == "broken" && previousState == "active")
                {
                    // ELEVATOR STATE CHANGED FROM ACTIVE TO BROKEN

                    var taskController = DependencyResolver.Current.GetService<TaskController>();
                    taskController.ControllerContext = new ControllerContext(this.Request.RequestContext, taskController);
                    string description = "Lifto būklė pasikeitė į " + Models.Elevator.StateName(state);
                    if (taskController.CreateTask(elevatorID, description))
                        TempData["EditSuccess"] += " Pridėta nauja užduotis.";
                }

                return RedirectToAction("DetailedElevatorInfo", new { id = elevatorID });

            }
            catch (Exception e)
            {
                TempData["error"] = e.Message + " 11";
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult ElevatorAPI(int id)
        {
            try
            {
                Models.ElevatorsDB db = new Models.ElevatorsDB();

Liftai0513/LiftaiMVC/Views/Elevators/DetailedElevatorInfo.cshtml
@model LiftaiMVC.Models.Elevator
@{
	ViewBag.Title = "DetailedElevatorInfo";
}
<h2>Detali lifto informacija</h2>
@if (TempData["EditSuccess"] != null)
{
	<div class="alert alert-success alert-dismissable">
		<strong>@TempData["EditSuccess"]</strong>
	</div>
}

@using (Html.BeginForm("DetailedElevatorInfo", "Elevators", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(m => m.SerialNum, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.SerialNum, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.SerialNum, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.Model, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.Model, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.Model, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.DeploymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.DeploymentDate, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.DeploymentDate, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.MaxWeight, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.MaxWeight, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.MaxWeight, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Stairway, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.Stairway, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.Stairway, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.LastCheckUp, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.LastCheckUp, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.LastCheckUp, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.CheckUpFrequency, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.CheckUpFrequency, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.CheckUpFrequency, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.BuildingID, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@if (ViewData["Buildings"] != null)
				{
					@Html.DropDownListFor(m => m.BuildingID, ViewData["Buildings"] as SelectList, new { @class = "form-control" })
					@Html.ValidationMessageFor(m => m.BuildingID, "", new { @class = "text-danger" })
				}
				else
				{
					<p>Nėra pastatų <a class="btn btn-default" href="@Url.Action("BuildingsList", "Buildings", new { id = @Model.BuildingID })">Eiti į pastatus &raquo;</a></p>
				}

			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.State, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EnumDropDownListFor(m => m.State, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.State, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.Notes, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				@if (HttpContext.Current.Session["Type"].ToString() == "Admin" || HttpContext.Current.Session["Type"].ToString() == "Handyman")
				{
					<input type="submit" value="Išsaugoti pakeitimus" class="btn btn-default" />
				}
				<a class="btn btn-default" href="@Url.Action("DetailedBuildingInfo", "Buildings", new { id = @Model.BuildingID })">Peržiūrėti pastatą &raquo;</a>
			</div>
		</div>
		@if (HttpContext.Current.Session["Type"].ToString() == "Operator")
		{
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<a class="btn btn-default" href="@Url.Action("RestartElevator", new { elevatorID = @Model.ID })">Perkrauti lifto sistemą &raquo;</a>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<a class="btn btn-default" href="@Url.Action("TurnOffBrakes", new { elevatorID = @Model.ID })">Išjungti avarinius stabdžius &raquo;</a>
				</div>
			</div>
		}
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<a class="btn btn-default" href="@Url.Action("ElevatorAPI", new { id = @Model.ID })">Lifto API &raquo;</a>

			</div>
		</div>
	</div>
}

@if (HttpContext.Current.Session["Type"].ToString() == "Handyman")
{
	<a class="btn btn-default" href="~/Home/IndexHandyman">Grįžti į pradžią &raquo;</a>
}

@if (HttpContext.Current.Session["Type"].ToString() == "Admin")
{
	<a class="btn btn-default" href="~/Elevators/ElevatorsList">Grįžti į sąrašą &raquo;</a>
}

Liftai0513/LiftaiMVC/Views/Elevators/ElevatorAPI.cshtml
@model LiftaiMVC.Models.Elevator

@{
    ViewBag.Title = "ElevatorAPI";
}

<h2>ElevatorAPI</h2>

<h3>Lifto sistemos perkrovimas: </h3>
<div class="form-group">
    <a class="btn btn-default" href="@Url.Action("RestartElevator", new { elevatorID = @Model.ID, restart = true })">Perkrovimas pavyko</a>
    <a class="btn btn-default" href="@Url.Action("RestartElevator", new { elevatorID = @Model.ID, restart = false })">Perkrovimas nepavyko</a>
</div>

<h3>Lifto būklės užklausai (avarinių stabdžių išjungimui): </h3>
<div class="form-group">
    <a class="btn btn-default" href="@Url.Action("TurnOffBrakes", new { elevatorID = @Model.ID, state = true })">Saugus naudoti</a>
    <a class="btn btn-default" href="@Url.Action("TurnOffBrakes", new { elevatorID = @Model.ID, state = false })">Nesaugus naudoti</a>
</div>

<h3>Lifto būklės pasikeitimo signalas: </h3>
<div class="form-group">
    <a class="btn btn-default" href="@Url.Action("NewState", new { elevatorID = @Model.ID, state = "stopped" })">Sustabdytas</a>
    <a class="btn btn-default" href="@Url.Action("NewState", new { elevatorID = @Model.ID, state = "broken" })">Sugedęs</a>
    <a class="btn btn-default" href="@Url.Action("NewState", new { elevatorID = @Model.ID, state = "active" })">Veikiantis</a>
</div>

<h3>Pagalbos signalai: </h3>
<div class="form-group">
    <a class="btn btn-default" href="@Url.Action("SystemFailure", new { elevatorID = @Model.ID })">Iškviesti pagalbą</a>
</div>

Liftai0513/LiftaiMVC/Views/Elevators/ElevatorForm.cshtml
@model LiftaiMVC.Models.Elevator
@{
	ViewBag.Title = "Naujas liftas";
}
<h2>Pridėti naują liftą</h2>

@if (TempData["SuccessMessage"] != null)
{
	<div class="alert alert-success alert-dismissable">
		<strong>@TempData["SuccessMessage"]</strong>
	</div>
}

@using (Html.BeginForm("ElevatorForm", "Elevators", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(m => m.SerialNum, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.SerialNum, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.SerialNum, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.Model, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.Model, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.Model, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.DeploymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.DeploymentDate, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.DeploymentDate, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.MaxWeight, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.MaxWeight, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.MaxWeight, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Stairway, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.Stairway, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.Stairway, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.LastCheckUp, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.LastCheckUp, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.LastCheckUp, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.CheckUpFrequency, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.CheckUpFrequency, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.CheckUpFrequency, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.BuildingID, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@if (ViewData["Buildings"] != null)
				{
					@Html.DropDownListFor(m => m.BuildingID, ViewData["Buildings"] as SelectList, new { @class = "form-control" })
					@Html.ValidationMessageFor(m => m.BuildingID, "", new { @class = "text-danger" })
				}
				else
				{
					<p>Nėra pastatų <a class="btn btn-default" href="~/Buildings/BuildingsList">Eiti į pastatus &raquo;</a></p>
				}

			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.State, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EnumDropDownListFor(m => m.State, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.State, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(m => m.Notes, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>
		<div class="form-group">

			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Išsaugoti" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div class="row">
	<p><a class="btn btn-default" href="~/Elevators/ElevatorsList">Grįžti į sąrašą &raquo;</a></p>

</div>

Liftai0513/LiftaiMVC/Views/Elevators/ElevatorsList.cshtml
@model IEnumerable<LiftaiMVC.Models.Elevator>
@{
	ViewBag.Title = "ElevatorsList";
}

<h2>Liftų sąrašas</h2>
<hr />
@if (HttpContext.Current.Session["Type"].ToString() == "Admin")
{
	<div class="row">
		<div class="col-lg-10">
			<p><a class="btn btn-default" href="~/Elevators/ElevatorForm">Kurti naują liftą &raquo;</a></p>
		</div>
	</div>
}
<table class="table">
	<tr>
		<th>Serijos numeris</th>
		<th>Modelis</th>
		<th>Būsena</th>
		<th>Paskutinė profilaktika</th>
		<th>Profilaktikos dažnumas</th>
		<th>Kita informacija</th>
		@if (HttpContext.Current.Session["Type"].ToString() == "Admin")
		{
			<th>Trinti įrašą</th>
		}

	</tr>
	@foreach (var item in Model)
	{
    <tr>
        <td>@item.SerialNum</td>
        <td>@item.Model</td>
        <td>@item.StateName()</td>
        <td>@item.LastCheckUp</td>
        <td>@item.CheckUpFrequency</td>
        <td>@Html.ActionLink("Detaliau", "DetailedElevatorInfo", new { id = item.ID })</td>
        @if (HttpContext.Current.Session["Type"].ToString() == "Admin")
        {
            <td>
                @Html.ActionLink("Trinti", "Delete", new { id = item.ID }, new { onclick = "return confirm('Ar tikrai norite ištrinti šį įrašą?');" })
            </td>
        }
    </tr>
	}
</table>